import { CreateBindingNodeByNodeFn } from "../DataBinding/BindingNode/types";
import { CreateBindingStateByStateFn } from "../DataBinding/BindingState/types";

/**
 * BindingBuilder モジュールの型定義ファイル。
 *
 * このファイルは、テンプレート内のバインディング情報を構造化して扱うための
 * インターフェースと型定義を提供します。
 * 
 * 主な型定義:
 * - NodeType: サポートするノード種別の列挙
 * - NodePath: ノードの位置を表す階層的なインデックス配列
 * - IBindText: パース済みバインディング式の構造化データ
 * - IFilterText: フィルター定義（名前とオプション）
 * - IDataBindAttributes: 1ノード分の完全なバインディング情報
 * - IBindingCreator: バインディングインスタンス生成関数群
 * 
 * Type definition file for BindingBuilder module.
 *
 * This file provides interfaces and type definitions for handling
 * binding information within templates in a structured manner.
 * 
 * Main type definitions:
 * - NodeType: Enumeration of supported node types
 * - NodePath: Hierarchical index array representing node position
 * - IBindText: Structured data of parsed binding expression
 * - IFilterText: Filter definition (name and options)
 * - IDataBindAttributes: Complete binding information for one node
 * - IBindingCreator: Set of binding instance creation functions
 */

/**
 * サポートするノード種別の型定義。
 * 
 * 各ノードタイプの説明:
 * - HTMLElement: 通常の HTML 要素（div, span, input など）
 *   data-bind 属性を持つことができる
 * 
 * - SVGElement: SVG 要素（svg, path, circle など）
 *   data-bind 属性を持つことができる
 * 
 * - Text: テキストコンテンツのバインディング
 *   実際にはコメントノード（<!-- @@:textContent:value -->）として表現され、
 *   実行時に実際のテキストノードに置換される
 * 
 * - Template: テンプレート（繰り返しや条件分岐）
 *   実際にはコメントノード（<!-- @@:for:items --> など）として表現され、
 *   実行時に動的なコンテンツに展開される
 * 
 * Type definition for supported node types.
 * 
 * Description of each node type:
 * - HTMLElement: Regular HTML elements (div, span, input, etc.)
 *   Can have data-bind attribute
 * 
 * - SVGElement: SVG elements (svg, path, circle, etc.)
 *   Can have data-bind attribute
 * 
 * - Text: Text content binding
 *   Actually represented as comment node (<!-- @@:textContent:value -->),
 *   replaced with actual text node at runtime
 * 
 * - Template: Template (loops or conditional branches)
 *   Actually represented as comment node (<!-- @@:for:items --> etc.),
 *   expanded into dynamic content at runtime
 */
export type NodeType = "HTMLElement" | "SVGElement" | "Text" | "Template";

/**
 * ノードの絶対パスを表す型定義。
 * 
 * 各要素はルートからの各階層での childNodes インデックスを表す。
 * 
 * 構造:
 * - 配列の各要素が階層ごとの childNodes インデックス
 * - 空配列 [] はルートノード自身を表す
 * - [1, 2] は root.childNodes[1].childNodes[2] を表す
 * 
 * 使用例:
 * ```typescript
 * // ルートノード自身
 * const rootPath: NodePath = [];
 * 
 * // ルートの最初の子ノード
 * const firstChild: NodePath = [0];
 * 
 * // ルートの2番目の子の3番目の子
 * const deepNode: NodePath = [1, 2];
 * ```
 * 
 * Type definition for absolute path of a node.
 * 
 * Each element represents childNodes index at each level from root.
 * 
 * Structure:
 * - Each array element is childNodes index for each level
 * - Empty array [] represents root node itself
 * - [1, 2] represents root.childNodes[1].childNodes[2]
 * 
 * Usage examples:
 * ```typescript
 * // Root node itself
 * const rootPath: NodePath = [];
 * 
 * // First child of root
 * const firstChild: NodePath = [0];
 * 
 * // Third child of second child of root
 * const deepNode: NodePath = [1, 2];
 * ```
 */
export type NodePath = number[];

/**
 * 1ノード分の完全なバインディング属性情報を表すインターフェース。
 * 
 * registerDataBindAttributes によって生成され、
 * テンプレート内の各バインディングノードの情報を保持する。
 * 
 * プロパティ説明:
 * - nodeType: ノードの種別（"HTMLElement" | "SVGElement" | "Text" | "Template"）
 * 
 * - nodePath: ノードのルートからの絶対パス（インデックス配列）
 *   例: [1, 2] は root.childNodes[1].childNodes[2]
 * 
 * - bindTexts: このノードに定義された全バインディング式の配列
 *   1つのノードに複数のバインディングを定義可能
 *   例: "value:name;class:active" → 2つの IBindText
 * 
 * - creatorByText: 各 IBindText に対応するバインディング生成関数のマップ
 *   実行時にバインディングインスタンスを生成するために使用
 * 
 * 使用例:
 * ```typescript
 * // HTML: <input data-bind="value:email;class:active" />
 * const attrs: IDataBindAttributes = {
 *   nodeType: "HTMLElement",
 *   nodePath: [0, 1],
 *   bindTexts: [
 *     { nodeProperty: "value", stateProperty: "email", ... },
 *     { nodeProperty: "class", stateProperty: "active", ... }
 *   ],
 *   creatorByText: new Map([
 *     [bindText1, { createBindingNode: ..., createBindingState: ... }],
 *     [bindText2, { createBindingNode: ..., createBindingState: ... }]
 *   ])
 * };
 * ```
 * 
 * Interface representing complete binding attribute information for one node.
 * 
 * Generated by registerDataBindAttributes,
 * holds information for each binding node within template.
 * 
 * Property descriptions:
 * - nodeType: Node type ("HTMLElement" | "SVGElement" | "Text" | "Template")
 * 
 * - nodePath: Absolute path from root (index array)
 *   Example: [1, 2] is root.childNodes[1].childNodes[2]
 * 
 * - bindTexts: Array of all binding expressions defined on this node
 *   Multiple bindings can be defined on one node
 *   Example: "value:name;class:active" → 2 IBindText objects
 * 
 * - creatorByText: Map of binding creation functions corresponding to each IBindText
 *   Used to create binding instances at runtime
 * 
 * Usage example:
 * ```typescript
 * // HTML: <input data-bind="value:email;class:active" />
 * const attrs: IDataBindAttributes = {
 *   nodeType: "HTMLElement",
 *   nodePath: [0, 1],
 *   bindTexts: [
 *     { nodeProperty: "value", stateProperty: "email", ... },
 *     { nodeProperty: "class", stateProperty: "active", ... }
 *   ],
 *   creatorByText: new Map([
 *     [bindText1, { createBindingNode: ..., createBindingState: ... }],
 *     [bindText2, { createBindingNode: ..., createBindingState: ... }]
 *   ])
 * };
 * ```
 */
export interface IDataBindAttributes {
  nodeType: NodeType;    // ノードの種別 / Node type
  nodePath: NodePath;    // ノードの絶対パス / Absolute path of node
  bindTexts: IBindText[]; // バインディング式の配列 / Array of binding expressions
  creatorByText: Map<IBindText, IBindingCreator>; // バインディング生成関数のマップ / Map of binding creation functions
}

/**
 * フィルター情報を表すインターフェース。
 * 
 * フィルターは状態値やノード値を変換する際に使用される。
 * 
 * プロパティ説明:
 * - name: フィルター名（例: "eq", "default", "currency"）
 *   組み込みフィルターまたはカスタムフィルターの名前
 * 
 * - options: フィルターに渡すオプション配列
 *   フィルターの動作をカスタマイズするパラメータ
 *   例: currency フィルターの ["USD", "2"] は通貨と小数点桁数
 * 
 * 使用例:
 * ```typescript
 * // "eq,100" → 値が100と等しいかチェック
 * const eqFilter: IFilterText = {
 *   name: "eq",
 *   options: ["100"]
 * };
 * 
 * // "default,N/A" → 値が空の場合に "N/A" を使用
 * const defaultFilter: IFilterText = {
 *   name: "default",
 *   options: ["N/A"]
 * };
 * 
 * // "currency,USD,2" → 金額を USD 形式で小数点2桁表示
 * const currencyFilter: IFilterText = {
 *   name: "currency",
 *   options: ["USD", "2"]
 * };
 * 
 * // "trim" → オプションなしのフィルター
 * const trimFilter: IFilterText = {
 *   name: "trim",
 *   options: []
 * };
 * ```
 * 
 * Interface representing filter information.
 * 
 * Filters are used to transform state values or node values.
 * 
 * Property descriptions:
 * - name: Filter name (e.g., "eq", "default", "currency")
 *   Name of built-in or custom filter
 * 
 * - options: Array of options passed to filter
 *   Parameters to customize filter behavior
 *   Example: ["USD", "2"] for currency filter means currency and decimal places
 * 
 * Usage examples:
 * ```typescript
 * // "eq,100" → Check if value equals 100
 * const eqFilter: IFilterText = {
 *   name: "eq",
 *   options: ["100"]
 * };
 * 
 * // "default,N/A" → Use "N/A" if value is empty
 * const defaultFilter: IFilterText = {
 *   name: "default",
 *   options: ["N/A"]
 * };
 * 
 * // "currency,USD,2" → Display amount in USD format with 2 decimal places
 * const currencyFilter: IFilterText = {
 *   name: "currency",
 *   options: ["USD", "2"]
 * };
 * 
 * // "trim" → Filter without options
 * const trimFilter: IFilterText = {
 *   name: "trim",
 *   options: []
 * };
 * ```
 */
export interface IFilterText {
  name: string; // フィルター名 / Filter name
  options: string[]; // フィルターオプションの配列 / Array of filter options
}

/**
 * パース済みバインディング式の構造化情報を表すインターフェース。
 * 
 * parseBindText によって生成され、バインディング式の全ての情報を保持する。
 * 
 * プロパティ説明:
 * - nodeProperty: バインディング対象のノードプロパティ名
 *   例: "textContent", "value", "class", "style", "for"
 * 
 * - stateProperty: バインディング元の状態プロパティ名
 *   ドット記法でネストしたプロパティも指定可能
 *   例: "user.name", "items", "config.theme.color"
 * 
 * - inputFilterTexts: 状態→ノード方向のフィルター配列
 *   状態の値がノードに表示される際に適用されるフィルター
 *   例: "value|currency,USD:amount" の "currency,USD"
 * 
 * - outputFilterTexts: ノード→状態方向のフィルター配列
 *   ノードの値が状態に反映される際に適用されるフィルター
 *   例: "value:email|lowercase" の "lowercase"
 * 
 * - decorates: デコレータ（追加機能）の配列
 *   バインディングに追加機能を付与する修飾子
 *   例: "required", "debounce", "throttle"
 * 
 * 使用例:
 * ```typescript
 * // 基本的なバインディング: "textContent:user.name"
 * const basicBind: IBindText = {
 *   nodeProperty: "textContent",
 *   stateProperty: "user.name",
 *   inputFilterTexts: [],
 *   outputFilterTexts: [],
 *   decorates: []
 * };
 * 
 * // フィルター付き: "value|currency,USD:amount"
 * const filteredBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "amount",
 *   inputFilterTexts: [{ name: "currency", options: ["USD"] }],
 *   outputFilterTexts: [],
 *   decorates: []
 * };
 * 
 * // デコレータ付き: "value:email@required,trim"
 * const decoratedBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "email",
 *   inputFilterTexts: [],
 *   outputFilterTexts: [],
 *   decorates: ["required", "trim"]
 * };
 * 
 * // 双方向フィルター: "value|trim:data.text|uppercase"
 * const bidirectionalBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "data.text",
 *   inputFilterTexts: [{ name: "trim", options: [] }],
 *   outputFilterTexts: [{ name: "uppercase", options: [] }],
 *   decorates: []
 * };
 * ```
 * 
 * Interface representing structured information of parsed binding expression.
 * 
 * Generated by parseBindText, holds all information of binding expression.
 * 
 * Property descriptions:
 * - nodeProperty: Node property name to bind
 *   Example: "textContent", "value", "class", "style", "for"
 * 
 * - stateProperty: State property name to bind from
 *   Can specify nested properties with dot notation
 *   Example: "user.name", "items", "config.theme.color"
 * 
 * - inputFilterTexts: Filter array for state→node direction
 *   Filters applied when state value is displayed on node
 *   Example: "currency,USD" in "value|currency,USD:amount"
 * 
 * - outputFilterTexts: Filter array for node→state direction
 *   Filters applied when node value is reflected to state
 *   Example: "lowercase" in "value:email|lowercase"
 * 
 * - decorates: Array of decorators (additional features)
 *   Modifiers to add additional features to binding
 *   Example: "required", "debounce", "throttle"
 * 
 * Usage examples:
 * ```typescript
 * // Basic binding: "textContent:user.name"
 * const basicBind: IBindText = {
 *   nodeProperty: "textContent",
 *   stateProperty: "user.name",
 *   inputFilterTexts: [],
 *   outputFilterTexts: [],
 *   decorates: []
 * };
 * 
 * // With filter: "value|currency,USD:amount"
 * const filteredBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "amount",
 *   inputFilterTexts: [{ name: "currency", options: ["USD"] }],
 *   outputFilterTexts: [],
 *   decorates: []
 * };
 * 
 * // With decorator: "value:email@required,trim"
 * const decoratedBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "email",
 *   inputFilterTexts: [],
 *   outputFilterTexts: [],
 *   decorates: ["required", "trim"]
 * };
 * 
 * // Bidirectional filters: "value|trim:data.text|uppercase"
 * const bidirectionalBind: IBindText = {
 *   nodeProperty: "value",
 *   stateProperty: "data.text",
 *   inputFilterTexts: [{ name: "trim", options: [] }],
 *   outputFilterTexts: [{ name: "uppercase", options: [] }],
 *   decorates: []
 * };
 * ```
 */
export interface IBindText {
  nodeProperty: string; // ノードプロパティ名 / Node property name
  stateProperty: string; // ステートプロパティ名 / State property name
  inputFilterTexts: IFilterText[]; // 入力フィルタの配列（状態→ノード） / Array of input filters (state→node)
  outputFilterTexts: IFilterText[]; // 出力フィルタの配列（ノード→状態） / Array of output filters (node→state)
  decorates: string[]; // デコレータの配列 / Array of decorators
}

/**
 * バインディングインスタンス生成関数群を表すインターフェース。
 * 
 * 各バインディングに対して、ノード側とステート側の
 * バインディングインスタンスを生成する関数を保持する。
 * 
 * プロパティ説明:
 * - createBindingNode: ノード側のバインディングインスタンス生成関数
 *   DOM ノードの変更を監視・制御するインスタンスを生成
 * 
 * - createBindingState: ステート側のバインディングインスタンス生成関数
 *   状態の変更を監視・伝播するインスタンスを生成
 * 
 * 使用例:
 * ```typescript
 * const creator: IBindingCreator = {
 *   createBindingNode: (node, bindText) => {
 *     // ノード側のバインディングを生成
 *     return new BindingNode(node, bindText);
 *   },
 *   createBindingState: (state, bindText) => {
 *     // ステート側のバインディングを生成
 *     return new BindingState(state, bindText);
 *   }
 * };
 * ```
 * 
 * Interface representing set of binding instance creation functions.
 * 
 * Holds functions to create binding instances for node side and state side
 * for each binding.
 * 
 * Property descriptions:
 * - createBindingNode: Binding instance creation function for node side
 *   Creates instance to monitor and control DOM node changes
 * 
 * - createBindingState: Binding instance creation function for state side
 *   Creates instance to monitor and propagate state changes
 * 
 * Usage example:
 * ```typescript
 * const creator: IBindingCreator = {
 *   createBindingNode: (node, bindText) => {
 *     // Create node side binding
 *     return new BindingNode(node, bindText);
 *   },
 *   createBindingState: (state, bindText) => {
 *     // Create state side binding
 *     return new BindingState(state, bindText);
 *   }
 * };
 * ```
 */
export interface IBindingCreator {
  createBindingNode: CreateBindingNodeByNodeFn; // ノード側バインディング生成関数 / Node side binding creation function
  createBindingState: CreateBindingStateByStateFn; // ステート側バインディング生成関数 / State side binding creation function
}